### ISSUE TITLE
[BUG] Using DnD on a placed word creates a shadow-copy of the word.

### ISSUE THREAD

**Issue by SkullCandyTV** [blmage/duolingo-word-bank-dnd#50]
**How to reproduce:** 

1. Place words in a word-bank question
2. Move one word to another position
3. The "real" word appears where you dropped it
4. A shadow-copy is created at the original place

**Problems:**

1. Happens every single time
2. Endless of times per word
3. Shadow-copies can't be moved, removed or avoided unless you don't use the extensions feature
4. Disorients the user extremely
5. Could lead to wrong sentences as people mix up real & fake copies

**Non-Problems:**

1. Copied words are invisible to the error-check
2. You can still correctly answer every question even with the bug
3. The main DnD-features still work

**Example:**

![image](https://github.com/blmage/duolingo-word-bank-dnd/assets/89059544/fd64282e-60d2-4bef-8f21-37e4948a4029)

**Comment by blmage** [comment]
Thanks for the detailed bug report!

This should be fixed in version **2.3.0**.

In any case, it's worth noting that unless you find the keyboard shortcuts valuable, you probably don't need the extension anymore, as the Duolingo UI now offers native drag and drop support!
