### ISSUE TITLE
Opera extension in the making?

### ISSUE THREAD

**Issue by dzittin** [blmage/duolingo-word-bank-dnd#6]
You have 1 vote for an Opera extension.

**Comment by blmage** [comment]
At first glance, it seems to only be a matter of submitting the extension to Opera Add-ons - I'll take care of that soon then!

**Comment by blmage** [comment]
The extension is now available on the Opera store!

https://addons.opera.com/fr/extensions/details/duolingo-word-bank-dnd/

I'll submit the others tomorrow - it'll probably be another week before they're validated.
